ministryofjustice/staff-technology-services-github-teams

- teams.tf
Closes ministryofjustice/cloud-operations#134
> :bento: add cloudops writers team

- teams.tf
changing memberships to members from maintainers
> :bento: update team members

- teams.tf
👋 Thank you for your service @yusufsheiqh.
> :busts_in_silhouette: Remove Yusuf

- teams.tf
Add the team as maintainers, additionally add the staff-infrastructure-moj account as a maintainer
> :wrench: Add maintainers

- teams.tf
Thank you for your service @MatthewWhiteMoJ 🙏
> :wrench: Remove Matt White from cloud-ops-admins

- teams.tf
updated members of the writers teams in code (members had been added manually).
> :passport_control: Update '-writers' team members

- teams.tf
Add David Sibley to nvvs-devops-admins team to assist with TGW Pipeline requests.
> :rocket: Add David Sibley to nvvs-devops-admins team

- teams.tf
> 🔥 remove myself from admins

- teams.tf
> :wrench: Added Satish to team's repos

- teams.tf
Also reordered team_members list a-z
> Added Dare to the team.

- teams.tf
New team members promoted from Github group members to maintainers.
> Add new team members as maintainers.

- teams.tf
- Removed team member who has left
- Added new repos to team
> Add team to juniper repos

- teams.tf
removed devops admins from tech-docs-monitor
> removed devops admins from tech-docs-monitor

- teams.tf
Email: Sandhya.Buddharaju@justice.gov.uk
> Addin new Admin team member Sandhya

- teams.tf
> Added Lauren Taylor-Brown to nvvs-devops-admins GitHub Team

- teams.tf
Suspect that the two MOJ admin staff have not logged in and have been auto removed from the org.
ND-162
> Commenting out tow users to unblock CI

- teams.tf
New engineer onboarding.
ND-162
> Adding Asif to the nvvs-devops-admins GitHub team

- teams.tf
> Removed user as no longer required access

- teams.tf
> Added John Nolan

- teams.tf
Required in order to subscribe new or missing repos to the notifications Slack channel.
> Promote Sandy from team to maintainer

- Makefile
> added make unlock to allow terraform to be unlocked.

- teams.tf
Add operations-engineering-servicenow to admin our repos
> ND-718 Added operations engineering service now

- teams.tf
Updated Mahmood GitHub Id to "m1moj" and Temporarity commented Asif from team due to ongoing GitHub Licensing issue
> ND-761 Updated Mahmood GitHub Id and Temporarity commented Asif

- teams.tf
Reverts ministryofjustice/staff-technology-services-github-teams#127
> Revert "Add Shahzad to Github team"

- teams.tf
Reverts ministryofjustice/staff-technology-services-github-teams#129
> Add Shahzad to Github team

- teams.tf
As part of the clean up users task from nvvs-devops.
Removed:
m1moj- Mahmood Mahmood, exited 09/05
Added:
SMAMoJ- @Shahid Mahmood 
Uncommented to add back:
asifamirat00
> ND-922 Added Shahid, removed mahmood and added asif back
